version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: pgdb
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
          interval: 5s
          timeout: 5s
          retries: 5
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

  fastapi:
    build: 
      context: .
      dockerfile: docker/fastapi/Dockerfile
    container_name: fastapi_container
    restart: always
    ports:
      - ${FASTAPI_PORT}:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
